version: "3"

services:
 
  
  kafka:
    image: 'bitnami/kafka:latest'
    network_mode: host
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9092"]
        interval: 30s
        timeout: 10s
        retries: 5

  
  lab:
    build: server/
    ports:
      - 1234:1234
    command: /bin/bash runner.sh
    network_mode: host

    restart: on-failure
    depends_on:
      - kafka
    
